.github/workflows/push.yml, .gitlint, .pre-commit-config.yaml, .travis.yml, README.md, requirements-dev.txt
Closes #3
* adds commit linting via [pre-commit](https://pre-commit.com/) and [gitlint](http://jorisroovers.com/gitlint/)
* `commit-msg` hook will check commit messages before they are commited locally
* continuous integration checks via GitHub Actions and Travis-CI will both check that all commits since `master` conform, not just the current commit (this prevents a non-conforming commit from being merged in an environment where the hooks are not installed)
=> feat: ensure commit messages conform to conventional commits

.pylintrc
This allows TODO: to be present in comments, it is useful to explain to future developers areas of concern inside of a codebase.
=> fix: allow TODO in comments

.gitlint, README.md
Adding more commit types:
* chore: e.g. adding a new file to `.gitignore`
* revert: for commits that only revert a previous commit
=> Add more commit types (chore and revert)

.gitlint
Fixes #12 
Rationale:
a) dependabot doesn't work with a maximum line length in the body
b) commitlint defaults to infinite line length in the body
c) most editors / terminals will wrap just fine anyway
=> Allow any line length for the optional body of commit messages

.github/workflows/ci.yml, README.md
Fixes #36
This change means that if a series of commits is pushed to GitHub on a branch or on master, `gitlint` will only check the most recent commit. It will still check all commits that are part of a Pull Request.
This should mean that `gitlint` doesn't "get in the way" unnecessarily, but still ensures conforming commits for the most common use cases.
=> ci: make gitlint more robust for different git workflows

.kodiak.toml, README.md
Add Kodiak to allow Pull Requests to be automatically merged with the `automerge :rocket:` label.
=> chore: add Kodiak configuration

.github/workflows/ci.yml
Closes #57
Deduplicate CI steps by combining "linter" and "test" jobs.
Target Python 3.8 for new Python projects.
=> ci: simplify CI steps and target Python 3.8 only

.github/dependabot.yml
GitHub's new dependabot doesn't appear to include `build (deps):` and `build(deps-dev)` prefixes in commit messages by default like the original service. Configure them in our template to ensure that new repositories based from it conform with conventional commits.
=> chore: configure dependabot to include prefixes in commit messages

.github/workflows/ci.yml
Rather than running a specific subset of linters, this keeps the results
in CI in sync with the results when committing.
=> feat: Run all pre-commit hooks in CI

.pre-commit-config.yaml, README.md
As far as I can tell there is no Python package for this, so I've used
the solution recommended by the official Prettier documentation
<https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit>.
I've specified a commit ID rather than a tag for security reasons - if
anyone manages to replace the tag with some malicious code we won't be
affected.
Closes https://github.com/linz/template-python-hello-world/issues/114
=> feat: Format files using Prettier

.pre-commit-config.yaml
Otherwise it tries to lint `.git/COMMIT_EDITMSG`.
=> fix: Run prettier only on commit stage

.pylintrc
This might be controversial, but a max line length of 127 seems excessive. 100 is already big enough that it's hard to have two readable files side by side.
=> chore: Use more default pylint settings

.github/workflows/ci.yml, README.md, poetry.lock, pyproject.toml
The template repo originally supported Python 3.6 onwards, which is a
bit limiting since packages like Black have removed support for 3.6
already. I'm guessing for the majority of projects we'd prefer them to
start with the latest stable version of Python, to have the most useful
set of features and packages. Only if necessary would users change the
supported range of Python versions.
=> feat: Support latest stable Python

pyproject.toml
These are all part of the default "black" profile
<https://pycqa.github.io/isort/docs/configuration/profiles.html>.
=> chore: Simplify isort settings

pyproject.toml
Avoids two issues:
- Having to change the include when renaming or adding a top-level
directory
- Not detecting the correct coverage when forgetting to update the
include list
=> feat: Exclude rather than include code for coverage

.github/workflows/ci.yml
Even though the build is not needed to merge, the GitHub UI still shows
it as a failure. This is misleading for reviewers. Unfortunately GitHub
Actions does not yet have any way to indicate that an error in a
specific job should not be considered as failing the pipeline
<https://github.com/actions/toolkit/issues/399>.
=> chore: Remove Python 3.10 build

.github/workflows/ci.yml
GitHub branch protection rules do not have a feature for specifying that
*all* workflow jobs must pass before the branch can be merged. Instead
we have to specify the job names explicitly. Since each job in a matrix
gets a different name, that means whenever the matrix is updated the
branch protection rule must be updated. To work around this we use a
non-matrix "finalise" job which checks that all dependent jobs passed.
Post-merge task:
=> feat: Create single summary test job

.github/workflows/codeql-analysis.yml
GitHub unfortunately disables workflows with a schedule on any repo without activity for 60 days. This disabling is silent and invisible, only showing up as a slightly different icon next to the job on the Actions page. Clicking that icon will prompt whether you want to re-enable it. But at that point the damage is already done, in shape of a lot of fiddling to figure out what went wrong, and having to re-push PRs with different contents to actually trigger the now active workflow.
There's been no response from GitHub about this issue yet <https://github.com/orgs/community/discussions/32197>.
This is part of fixing
<https://github.com/linz/ds-infra-team/issues/927>.
=> fix: Remove workflow schedule

.github/workflows/ci.yml, README.md, poetry.lock, pyproject.toml
This drops support for Python 3.7, which is EOL.
=> build: Bump minimum Python version

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/mutation-testing.yml
Done with pin-github-action <https://github.com/mheap/pin-github-action> 1.8.0 using `npx pin-github-action .github/workflows/*.y*ml`.
Dependabot should support updating in the same fashion <https://github.com/dependabot/dependabot-core/issues/8277#issuecomment-1782819752>.
Had to `export GH_ADMIN_TOKEN=github_pat_…` using a fine-grained personal access tokens with no extra access to work around rate limiting *and* to be able to work in private repos
<https://github.com/mheap/pin-github-action/issues/73>.
=> feat: Pin actions to hashes TDE-934

README.md
It's since been integrated into GitHub's CodeQL.
=> chore: Remove references to discontinued lgtm.com service

.github/workflows/ci.yml, .github/workflows/mutation-testing.yml
`python -m …` is only necessary if more than one Python version is installed, and we need to specify the Python executable explicitly.
=> refactor: Simplify Python package install

.github/workflows/ci.yml, .github/workflows/mutation-testing.yml, README.md
Avoids the following:
```
Installing the current project: […]
Warning: The current project could not be installed: No file/folder found for package […]
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
```
=> fix: Don't attempt to install project inside virtualenv
